export const bookCategories = [
  { value: 'fiction', label: 'Художня література' },
  { value: 'nonfiction', label: 'Документальна' },
  { value: 'fantasy', label: 'Фентезі' },
  { value: 'sci-fi', label: 'Наукова фантастика' },
  { value: 'detective', label: 'Детектив' },
  { value: 'romance', label: 'Романтика' },
  { value: 'thriller', label: 'Трилер' },
  { value: 'history', label: 'Історична література' },
  { value: 'biography', label: 'Біографія / Мемуари' },
  { value: 'selfhelp', label: 'Саморозвиток' },
  { value: 'psychology', label: 'Психологія' },
  { value: 'philosophy', label: 'Філософія' },
  { value: 'poetry', label: 'Поезія' },
  { value: 'children', label: 'Дитяча література' },
  { value: 'young-adult', label: 'Підліткова література' },
  { value: 'science', label: 'Наукова література' },
  { value: 'religion', label: 'Релігія / Духовність' },
  { value: 'classic', label: 'Класика' },
  { value: 'horror', label: 'Жахи' },
  { value: 'adventure', label: 'Пригоди' },
  { value: 'drama', label: 'Драма' },
  { value: 'humor', label: 'Гумор / Сатира' },
  { value: 'art', label: 'Мистецтво / Фото' },
  { value: 'travel', label: 'Подорожі' },
  { value: 'cookbook', label: 'Кулінарія' },
  { value: 'business', label: 'Бізнес / Економіка' },
  { value: 'technology', label: 'Технології / ІТ' },
  { value: 'guide', label: 'Путівники / Довідники' },
  { value: 'education', label: 'Освіта / Підручники' },
  { value: 'health', label: 'Здоровʼя / Медицина' },
  { value: 'language', label: 'Мовознавство / Вивчення мов' },
  { value: 'politics', label: 'Політика / Соціологія' },
  { value: 'other', label: 'Інше' },
];
