import { BookSearchResponse } from '../types/BookSearchResponse';
import { Book } from '../types/Book';

const allBooks: Book[] = [
  {
    id: 1,
    ownerId: 1,
    title: 'Кобзар',
    author: 'Тарас Шевченко',
    coverImage:
      'http://books.google.com/books/content?id=T3GSEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    city: 'Київ',
    categoryName: 'Фентезі',
    condition: 'Новий',
    exchangeType: 'Обмін',
  },
  {
    id: 2,
    ownerId: 1,
    title: 'Як завойовувати друзів та впливати на людей',
    author: 'Дейл Карнегі',
    coverImage: 'https://covers.openlibrary.org/b/id/8022066-L.jpg',
    city: 'Львів',
    categoryName: 'Саморозвиток',
    condition: 'Б/у',
    exchangeType: 'Обмін',
  },
  {
    id: 3,
    ownerId: 1,
    title: '1984',
    author: 'Джордж Орвелл',
    coverImage: 'https://covers.openlibrary.org/b/id/7222247-L.jpg',
    city: 'Одеса',
    categoryName: 'Антиутопія',
    condition: 'Новий',
    exchangeType: 'Обмін',
  },
  {
    id: 4,
    ownerId: 1,
    title: 'Убити пересмішника',
    author: 'Гарпер Лі',
    coverImage: 'https://covers.openlibrary.org/b/id/978051-L.jpg',
    city: 'Дніпро',
    categoryName: 'Класика',
    condition: 'Б/у',
    exchangeType: 'Подарунок',
  },
  {
    id: 5,
    ownerId: 1,
    title: 'Великий Гетсбі',
    author: 'Ф. С. Фіцджеральд',
    coverImage: 'https://covers.openlibrary.org/b/id/7225131-L.jpg',
    city: 'Харків',
    categoryName: 'Класика',
    condition: 'Новий',
    exchangeType: 'Обмін',
  },
  {
    id: 6,
    ownerId: 1,
    title: 'Гордість і упередження',
    author: 'Джейн Остін',
    coverImage: 'https://covers.openlibrary.org/b/id/7985366-L.jpg',
    city: 'Вінниця',
    categoryName: 'Романтика',
    condition: 'Б/у',
    exchangeType: 'Обмін',
  },
  {
    id: 7,
    ownerId: 1,
    title: 'Мобі Дік',
    author: 'Герман Мелвілл',
    coverImage: 'https://covers.openlibrary.org/b/id/8221786-L.jpg',
    city: 'Запоріжжя',
    categoryName: 'Пригоди',
    condition: 'Новий',
    exchangeType: 'Подарунок',
  },
  {
    id: 8,
    ownerId: 1,
    title: 'Війна і мир',
    author: 'Лев Толстой',
    coverImage: 'https://covers.openlibrary.org/b/id/8197541-L.jpg',
    city: 'Чернігів',
    categoryName: 'Історичний роман',
    condition: 'Б/у',
    exchangeType: 'Обмін',
  },
  {
    id: 9,
    ownerId: 1,
    title: 'Як завойовувати друзів (extended)',
    author: 'Автор з довгим імʼям',
    coverImage: 'https://covers.openlibrary.org/b/id/8223818-L.jpg',
    city: 'Полтава',
    categoryName: 'Класика',
    condition: 'Новий',
    exchangeType: 'Обмін',
  },
  {
    id: 10,
    ownerId: 1,
    title: 'Злочин і кара',
    author: 'Ф. Достоєвський',
    coverImage: 'https://covers.openlibrary.org/b/id/8283947-L.jpg',
    city: 'Івано-Франківськ',
    categoryName: 'Психологічний роман',
    condition: 'Б/у',
    exchangeType: 'Подарунок',
  },
  {
    id: 11,
    ownerId: 1,
    title: 'Чапаєв і Пустота',
    author: 'Віктор Пєлєвін',
    coverImage: 'https://covers.openlibrary.org/b/id/9999999-L.jpg',
    city: 'Тернопіль',
    categoryName: 'Постмодерн',
    condition: 'Новий',
    exchangeType: 'Обмін',
  },
  {
    id: 12,
    ownerId: 1,
    title: 'Камю. Чума',
    author: 'Альбер Камю',
    coverImage: 'https://covers.openlibrary.org/b/id/8888888-L.jpg',
    city: 'Луцьк',
    categoryName: 'Екзистенціалізм',
    condition: 'Б/у',
    exchangeType: 'Обмін',
  },
  {
    id: 13,
    ownerId: 1,
    title: 'Кобзар',
    author: 'Тарас Шевченко',
    coverImage:
      'http://books.google.com/books/content?id=T3GSEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    city: 'Київ',
    categoryName: 'Фентезі',
    condition: 'Новий',
    exchangeType: 'Обмін',
  },
  {
    id: 14,
    ownerId: 1,
    title: 'Як завойовувати друзів та впливати на людей',
    author: 'Дейл Карнегі',
    coverImage: 'https://covers.openlibrary.org/b/id/8022066-L.jpg',
    city: 'Львів',
    categoryName: 'Саморозвиток',
    condition: 'Б/у',
    exchangeType: 'Обмін',
  },
  {
    id: 15,
    ownerId: 1,
    title: '1984',
    author: 'Джордж Орвелл',
    coverImage: 'https://covers.openlibrary.org/b/id/7222247-L.jpg',
    city: 'Одеса',
    categoryName: 'Антиутопія',
    condition: 'Новий',
    exchangeType: 'Обмін',
  },
  {
    id: 16,
    ownerId: 1,
    title: 'Убити пересмішника',
    author: 'Гарпер Лі',
    coverImage: 'https://covers.openlibrary.org/b/id/978051-L.jpg',
    city: 'Дніпро',
    categoryName: 'Класика',
    condition: 'Б/у',
    exchangeType: 'Подарунок',
  },
  {
    id: 17,
    ownerId: 1,
    title: 'Великий Гетсбі',
    author: 'Ф. С. Фіцджеральд',
    coverImage: 'https://covers.openlibrary.org/b/id/7225131-L.jpg',
    city: 'Харків',
    categoryName: 'Класика',
    condition: 'Новий',
    exchangeType: 'Обмін',
  },
  {
    id: 18,
    ownerId: 1,
    title: 'Гордість і упередження',
    author: 'Джейн Остін',
    coverImage: 'https://covers.openlibrary.org/b/id/7985366-L.jpg',
    city: 'Вінниця',
    categoryName: 'Романтика',
    condition: 'Б/у',
    exchangeType: 'Обмін',
  },
  {
    id: 19,
    ownerId: 1,
    title: 'Мобі Дік',
    author: 'Герман Мелвілл',
    coverImage: 'https://covers.openlibrary.org/b/id/8221786-L.jpg',
    city: 'Запоріжжя',
    categoryName: 'Пригоди',
    condition: 'Новий',
    exchangeType: 'Подарунок',
  },
  {
    id: 20,
    ownerId: 1,
    title: 'Війна і мир',
    author: 'Лев Толстой',
    coverImage: 'https://covers.openlibrary.org/b/id/8197541-L.jpg',
    city: 'Чернігів',
    categoryName: 'Історичний роман',
    condition: 'Б/у',
    exchangeType: 'Обмін',
  },
  {
    id: 21,
    ownerId: 1,
    title: 'Як завойовувати друзів (extended)',
    author: 'Автор з довгим імʼям',
    coverImage: 'https://covers.openlibrary.org/b/id/8223818-L.jpg',
    city: 'Полтава',
    categoryName: 'Класика',
    condition: 'Новий',
    exchangeType: 'Обмін',
  },
  {
    id: 22,
    ownerId: 1,
    title: 'Злочин і кара',
    author: 'Ф. Достоєвський',
    coverImage: 'https://covers.openlibrary.org/b/id/8283947-L.jpg',
    city: 'Івано-Франківськ',
    categoryName: 'Психологічний роман',
    condition: 'Б/у',
    exchangeType: 'Подарунок',
  },
  {
    id: 23,
    ownerId: 1,
    title: 'Чапаєв і Пустота',
    author: 'Віктор Пєлєвін',
    coverImage: 'https://covers.openlibrary.org/b/id/9999999-L.jpg',
    city: 'Тернопіль',
    categoryName: 'Постмодерн',
    condition: 'Новий',
    exchangeType: 'Обмін',
  },
  {
    id: 24,
    ownerId: 1,
    title: 'Камю. Чума',
    author: 'Альбер Камю',
    coverImage: 'https://covers.openlibrary.org/b/id/8888888-L.jpg',
    city: 'Луцьк',
    categoryName: 'Екзистенціалізм',
    condition: 'Б/у',
    exchangeType: 'Обмін',
  },
];

export function getMockBooksByPage(
  page: number,
  size: number
): BookSearchResponse {
  const totalElements = allBooks.length;
  const totalPages = Math.ceil(totalElements / size);
  const start = page * size;
  const end = start + size;
  const content = allBooks.slice(start, end);
  const hasNext = page < totalPages - 1;

  return {
    content,
    totalElements,
    totalPages,
    pageNumber: page,
    pageSize: size,
    hasNext,
  };
}
